[connections.supabase]
SUPABASE_URL = "https://ktftfxhmmkdcrewnthzf.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0ZnRmeGhtbWtkY3Jld250aHpmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MjQ4MDAyNCwiZXhwIjoyMDU4MDU2MDI0fQ.Qe_FEbBxwyVE-HApygmmyPPZZbu8KNysJmLSNAqn7dc"